version: '3.8'

services:
  floodless-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - oracle-db
    networks:
      - floodless-network

  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCL
      - ORACLE_PWD=${DB_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - floodless-network

volumes:
  oracle-data:

networks:
  floodless-network:
    driver: bridge 